# Generated by Django 3.2.16 on 2022-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, verbose_name='name')),
                ('vehicle_type', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=20)),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Model')),
                ('vehicle_description', models.TextField(verbose_name='Description about the vehicle.')),
            ],
        ),
    ]
